name: Docker Image CI

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Get release version
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(echo $GITHUB_SHA | cut -c1-7)
        fi
        
        VERSION=${VERSION#v}
        
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Release version: $VERSION"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          jlevangie/lazydj:${{ steps.get_version.outputs.RELEASE_VERSION }}
          jlevangie/lazydj:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
