name: Build Docker Image

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: docker.io
  IMAGE_NAME: jlevangie/lazydj

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Generate tags
      id: tags
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          echo "tags=${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }},${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
        else
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "tags=${{ env.IMAGE_NAME }}:main-${SHORT_SHA},${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.tags.outputs.tags }}

    - name: Image digest
      run: echo ${{ steps.build-and-push.outputs.digest }}